#cloud-config

users:
  - name: kube-bootstrap-logs-forwarder
    gecos: User the kube-bootstrap-logs-forwarder.service runs as.
    system: true
    shell: /sbin/nologin

write_files:
  - path: /etc/systemd/system/kube-bootstrap-logs-forwarder.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Forwards Kubernetes bootstrap logs to serial port.
      Before=setup-kubernetes-dir.service

      [Service]
      User=kube-bootstrap-logs-forwarder
      Group=systemd-journal
      SupplementaryGroups=serial
      ExecStart=journalctl --no-tail --no-pager --follow --utc --output short-iso --unit setup-kubernetes-dir --unit placeholders-presuspend-setup --unit kube-node-installation --unit kube-node-configuration --unit kubelet  --unit gcfsd --unit gcfs-snapshotter
      StandardOutput=tty
      TTYPath=/dev/ttyS2

      [Install]
      WantedBy=kubernetes.target

  - path: /etc/systemd/system/setup-kubernetes-dir.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Sets up required directories and mounts.
      After=network-online.target

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/bin/mkdir -p /home/kubernetes/bin
      ExecStart=/bin/mount --bind /home/kubernetes/bin /home/kubernetes/bin
      ExecStart=/bin/mount -o remount,exec /home/kubernetes/bin

      [Install]
      WantedBy=kubernetes.target

  - path: /etc/systemd/system/placeholders-presuspend-setup.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Perform required presuspend logic for Placeholders VM, skip for Non-Placeholders VMs.
      After=setup-kubernetes-dir.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecCondition=/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /home/kubernetes/bin/placeholders-presuspend.sh http://metadata.google.internal/computeMetadata/v1/instance/attributes/placeholders-presuspend-sh
      ExecStartPre=/bin/chmod 544 /home/kubernetes/bin/placeholders-presuspend.sh
      ExecStart=/home/kubernetes/bin/placeholders-presuspend.sh

      [Install]
      WantedBy=kubernetes.target


  - path: /etc/systemd/system/kube-node-installation.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Download and install k8s binaries and configurations
      After=placeholders-presuspend-setup.service

      [Service]
      Environment=KUBERNETES_MASTER=false
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=/usr/bin/curl --fail --retry 5 --retry-delay 3 --silent --show-error -H "X-Google-Metadata-Request: True" -o /home/kubernetes/bin/configure.sh http://metadata.google.internal/computeMetadata/v1/instance/attributes/configure-sh
      ExecStartPre=/bin/chmod 544 /home/kubernetes/bin/configure.sh
      ExecStart=/home/kubernetes/bin/configure.sh

      [Install]
      WantedBy=kubernetes.target

  - path: /etc/systemd/system/gke-node-reg-checker.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Check node registration with API server
      After=kube-node-installation.service

      [Service]
      Type=simple
      ExecStart=/home/kubernetes/bin/node-registration-checker.sh
      StandardOutput=journal+console
      ExecStartPre=/bin/chmod 544 /home/kubernetes/bin/node-registration-checker.sh

      [Install]
      WantedBy=kubernetes.target

  - path: /etc/systemd/system/kube-node-configuration.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Configure kubernetes node
      After=kube-node-installation.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStartPre=/bin/chmod 544 /home/kubernetes/bin/configure-helper.sh
      ExecStart=/home/kubernetes/bin/configure-helper.sh
      ExecStartPost=systemctl stop kube-bootstrap-logs-forwarder.service

      [Install]
      WantedBy=kubernetes.target

  - path: /etc/systemd/system/kube-logrotate.timer
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Hourly kube-logrotate invocation

      [Timer]
      OnCalendar=hourly

      [Install]
      WantedBy=kubernetes.target

  - path: /etc/systemd/system/kube-logrotate.service
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Kubernetes log rotation
      After=kube-node-configuration.service

      [Service]
      Type=oneshot
      # The relative path is being used as the path is different between image types - for example between Ubuntu and COS. See ExecSearchPath for allowed paths.
      ExecSearchPath=/usr/bin:/usr/sbin
      ExecStart=logrotate /etc/logrotate.conf

      [Install]
      WantedBy=kubernetes.target

  - path: /etc/systemd/system/kubernetes.target
    permissions: '0644'
    owner: root
    content: |
      [Unit]
      Description=Kubernetes

      [Install]
      WantedBy=multi-user.target

  - path: /etc/modprobe.d/sunrpc.conf
    permissions: '0644'
    owner: root
    # The GKE metadata server uses ports 987-989, so the sunrpc range should be restricted to be below.
    content: |
      options sunrpc max_resvport=986

runcmd:
  - systemctl enable
      kube-bootstrap-logs-forwarder.service
      setup-kubernetes-dir.service
      placeholders-presuspend-setup.service
      kube-node-installation.service
      gke-node-reg-checker.service
      kube-node-configuration.service
      kube-logrotate.timer
      kube-logrotate.service
      kubernetes.target
  - systemctl start kubernetes.target
